Hw 9
DashaChibisova/niffler-st4 pull request #6
Opened 2024-02-05 06:19 UTC by DashaChibisova

2024-02-05 08:16 UTC, sashkir7 requested changes
Необходимо внести ряд правок:
1. Мне кажется, что неверно написали логику удаления (см комментарии)
2. Данные в store нужно класть под уникальным для теста id. Это важно!

2024-02-05 08:16 UTC, sashkir7 commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/db/repository/SpendRepository.java
> +    SpendEntity createInSpend(SpendEntity spend);
Можно переименовать на create. Из контекста и так понятно, что речь о тратах

2024-02-05 08:16 UTC, sashkir7 commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/db/repository/SpendRepository.java
> +    void deleteInSpendByCategoryId(UUID id);
А здесь - deleteSpendsByCategoryId(UUID categoryID)

2024-02-05 08:16 UTC, sashkir7 commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/db/repository/SpendRepositoryHibernate.java
> +        persist(SPEND, spend);
Не нужно отдельно создавать категорию, отдельно трату
Хватит записи persist(SPEND, spend). Hibernate сам все должен создать (если нужно) "под капотом"

2024-02-05 08:16 UTC, sashkir7 commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/db/repository/SpendRepositoryHibernate.java
> +        CategoryEntity toBeDeletedCategory = Optional.of(entityManager(SPEND).find(CategoryEntity.class, id)).get();
А если такой категории не будет? Мы на get() упадем с NPE

2024-02-05 08:16 UTC, sashkir7 commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/db/repository/SpendRepositoryHibernate.java
> +                .setParameter("id", toBeDeletedCategory.getId()).getSingleResult()).get();
А если у нас несколько трат с такой категорией?

2024-02-05 08:16 UTC, sashkir7 commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/db/repository/SpendRepository.java
> +    void deleteInSpendByCategoryId(UUID id);
И вообще, как мне кажется, мы должны завязываться не на категории, а на пользователе. Грубо говоря, у нас каждый тест - это некий новый динамически созданный пользователь с теми или иными данными. Поэтому есть шанс, что мы удалим все по категории и потрем данные других пользователей, чего быть не должно. Либо я ход мыслей не так понял

2024-02-05 08:16 UTC, sashkir7 commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/db/repository/SpendRepositoryHibernate.java
> +        remove(SPEND, toBeDeletedCategory);
Можно в entity категории указать, чтобы при ее удалении было каскадное удаление связанной сущности (категории) (если она только для этой траты создана, конечно же)

2024-02-05 08:16 UTC, sashkir7 commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/db/repository/SpendRepositoryHibernate.java
> +        remove(SPEND, toBeDeletedCategory);
Много моментов. Я бы советовал сначала реализовать работу без удаления. А удаление "прикрутить" потом

2024-02-05 08:16 UTC, sashkir7 commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/jupiter/DatabaseSpendExtension.java
> +        GenerateCategory categoryData = methods.get(0).getAnnotation(GenerateCategory.class);
А для чего тогда before-each методы добавляем?
Если мы всегда берем элемент под индексом 0, то есть наш context.getRequiredTestMethod()

2024-02-05 08:16 UTC, sashkir7 commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/jupiter/DatabaseSpendExtension.java
> +                    .put("spend", create(spendJson));
В store нужно класть под уникальным для теста id
Это важно! Чтобы при параллельном запуске тестов не было конфликтов (чтобы разные потоки не переиспользовали\перетирали одну и ту же сущность)

2024-02-05 08:16 UTC, sashkir7 commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/jupiter/RestSpendExtension.java
> +                    .put("spend", created);
Аналогично

2024-02-05 13:35 UTC, DashaChibisova commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/db/repository/SpendRepository.java
> +    void deleteInSpendByCategoryId(UUID id);
насколько я поняла, каждая категория создается отдельно каждым пользователем и другим пользователям она не доступна  и соответсвенно связана категория и спендинг  либо айди , либо юзернеймом, и подумала, что если мы завяжемся на удаление по юзернейму, то можем удалить не тот спендинг/категорию, которые хотим заодно. Лучше завязываться на юзернейм?

2024-02-05 13:44 UTC, DashaChibisova commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/db/repository/SpendRepositoryHibernate.java
> +        persist(SPEND, spend);
а здесь пробовала без 21 строчки, но у меня выходит Method threw 'jakarta.persistence.RollbackException' exception.    java.lang.IllegalStateException: org.hibernate.TransientPropertyValueException: object references an unsaved transient instance - save the transient instance before flushing : guru.qa.niffler.db.model.SpendEntity.category -> guru.qa.niffler.db.model.CategoryEntity

2024-02-05 13:46 UTC, DashaChibisova commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/db/repository/SpendRepositoryHibernate.java
> +        persist(SPEND, spend);
вероятно, здесь как-то по-другому тогда нужно реализовывать?

2024-02-06 11:51 UTC, sashkir7 commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/db/repository/SpendRepository.java
> +    void deleteInSpendByCategoryId(UUID id);
Пользователь (юзер) - та сущность, вокруг которой "все крутится". То есть это самая главная наша сущность. Работая с категориями, я бы отталкивался от пользователя:
- мы добавляем категорию для конкретного пользователя
- мы можем получить категории конкретного пользователя
- мы можем удалить все категории у конкретного пользователя и тд

"если мы завяжемся на удаление по юзернейму, то можем удалить не тот спендинг/категорию" - у нас удаление сущностей происходит после прохождения теста. То есть, как мне кажется, можно смело удалять все, что связано с пользователем.

2024-02-06 11:52 UTC, sashkir7 commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/db/repository/SpendRepositoryHibernate.java
> +        persist(SPEND, spend);
Посмотрю. Отпишусь

2024-02-06 11:54 UTC, sashkir7 commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/db/repository/SpendRepositoryHibernate.java
> +        persist(SPEND, spend);
Попробуйте использовать cascade=CascadeType.ALL
[Источник тут](https://stackoverflow.com/questions/2302802/how-to-fix-the-hibernate-object-references-an-unsaved-transient-instance-save)

2024-02-06 11:54 UTC, sashkir7 commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/db/repository/SpendRepositoryHibernate.java
> +        persist(SPEND, spend);
Указывается в аннотации (по ссылке выше есть пример)

2024-02-06 12:02 UTC, sashkir7 approved these changes
Хорошо. На комментарии ответил
Также, если будет желание - обработать кейс, когда мы хотим добавить трату с уже существующей категорией. То есть, если указанная категория уже есть в БД, то дублировать ее не нужно

2024-02-06 12:02 UTC, sashkir7 commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/jupiter/DatabaseSpendExtension.java
> +        Method methods = context.getRequiredTestMethod();
methods - это не множ число. Просто method

2024-02-06 14:11 UTC, merged